#!/usr/bin/perl

use strict;

delete @ENV{qw(IFS CDPATH ENV BASH_ENV)};
$ENV{PATH}='/sbin';

use Vrane::EC2;
use Getopt::Long;
my ($delete, $region);
GetOptions(
	'region'     => \$region,
	"delete"     => \$delete ) or die "Cannot parse options\n";

my $ec2 = Vrane::EC2->new( region => $region );
my (%i) = map { $_ => 1 } $ec2->describe_images;
my (@s) = $ec2->describe_snapshots;
my @free;
for (@s){
	if($_->description =~ /\W for (ami-\w{8}) fro/){
		next if $i{$1};
		push @free, $_
	}
}
print "The following snapshots were created for AMI but the AMI are not registered\n" if @free;
for (@free){
	printf "%s %s %s\n",$_ , $_->description, $_->startTime;
	if($delete){
		print "deleting $_\n";
		$ec2->delete_snapshot($_) or warn "Failed to delete $_\n"
	}
}

